# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#           model_path: str optional (only for local inference)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int
#     system_prompt: str optional (add system instruction when generating model answer)
#     output_structured: str optional (add json format for structured answer generation) providing a path to the file with structured configuration

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

qwen-2.5-7b-base:
    model_name: Qwen2.5-7B-Instruct
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: 123
    api_type: openai
    system_prompt: "You are a helpful assistant, answer the user's question accurately and concisely."
    parallel: 4

qwen-2.5-7b-int4:
    model_name: Qwen2.5-7B-Instruct-GPTQ-Int4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: 123
    api_type: openai
    system_prompt: "You are a helpful assistant, answer the user's question accurately and concisely."
    parallel: 4

qwen-2.5-7b-int8:
    model_name: Qwen2.5-7B-Instruct-GPTQ-Int8
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: 123
    api_type: openai
    system_prompt: "You are a helpful assistant, answer the user's question accurately and concisely."
    parallel: 4

qwen-2.5-7b-awq:
    model_name: Qwen2.5-7B-Instruct-AWQ
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: 123
    api_type: openai
    system_prompt: "You are a helpful assistant, answer the user's question accurately and concisely."
    parallel: 4

falcon-7b-base:
    model_name: Falcon3-7B-Instruct
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: 123
    api_type: openai
    system_prompt: "You are a helpful assistant, answer the user's question accurately and concisely."
    parallel: 4

falcon-7b-int4:
    model_name: Falcon3-7B-Instruct-GPTQ-Int4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: 123
    api_type: openai
    system_prompt: "You are a helpful assistant, answer the user's question accurately and concisely."
    parallel: 4

falcon-7b-int8:
    model_name: Falcon3-7B-Instruct-GPTQ-Int8
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: 123
    api_type: openai
    system_prompt: "You are a helpful assistant, answer the user's question accurately and concisely."
    parallel: 4

falcon-7b-awq:
    model_name: Falcon3-7B-Instruct-AWQ
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: 123
    api_type: openai
    system_prompt: "You are a helpful assistant, answer the user's question accurately and concisely."
    parallel: 4