name: config of answer generation for brain-hard-v0.1

bench_name: brain-hard-v0.1

temperature: 0.0
max_tokens: 1024
num_choices: 1

# a list of model to generate answers
model_list:
    - qwen-2.5-7b-base
    - qwen-2.5-7b-int4
    - qwen-2.5-7b-int8
    - falcon-7b-base
