name: config of answer generation for brain-hard-v0.1

bench_name: brain-hard-v0.1

temperature: 0.0
max_tokens: 1024
num_choices: 1

# a list of model to generate answers
model_list:
    # Qwen-2.5-7B
    - qwen-2.5-7b-base
    - qwen-2.5-7b-int4
    - qwen-2.5-7b-int8
    - qwen-2.5-7b-awq
    # Falcon-7B
    - falcon-7b-base
    - falcon-7b-int4
    - falcon-7b-int8
    - falcon-7b-awq
    # Llama-3.2-3B-Instruct
    - llama-3.2-3b-base
    - llama-3.2-3b-awq
    - llama-3.2-3b-gptq-int4
    #- llama-3.2-3b-gptq-int8
    #- llama-3.2-3b-fp8-kv
